name: BSD
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  freebsd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Build
      # CodeQL security: uses should use an immutable tag or hash for untrusted actions, "@v1" may mutate
      uses: vmactions/freebsd-vm@v1.1.7
      with:
        # BSD make -j has a mandatory argument
        # Linux make -j means infinite jobs
        run: |
          pkg update
          pkg install -y autoconf automake bison flex pkgconf
          ./autogen.sh
          ./configure
          make -j $(nproc)
          make -j $(nproc) dist-xz
          make -j $(nproc) install
