name: BSD
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  freebsd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Build
      uses: vmactions/freebsd-vm@v1
      with:
        run: |
          pkg update
          pkg install -y autoconf automake bison flex pkgconf
          ./autogen.sh
          ./configure
          make -j
          make -j dist-xz
          make -j install
